### ISSUE TITLE
Powerline charater not getting printed properly

### ISSUE THREAD

**Issue by Compro-Prasad** [xuchunyang/eshell-git-prompt#2]
![screenshot from 2017-02-06 18-03-21](https://cloud.githubusercontent.com/assets/11143962/22647312/c4daffe0-ec96-11e6-8a4c-d76ad21239ac.png)

**Comment by xuchunyang** [comment]
The characters can be displayed here by using the Source Code Pro font, thus I guess you can try to fix it by using some fonts which support these characters.
