### ISSUE TITLE
how to limit the POWERLINE prompt to the last directory only

### ISSUE THREAD

**Issue by rileyrg** [xuchunyang/eshell-git-prompt#8]
great package. But  I would like to limit the POWERLINE prompt to the last directory only as its way too long.

Ideally you could use the actual theme prompt or respect the ENV 

`POWERLEVEL9K_SHORTEN_DIR_LENGTH=1`

![Screenshot from 2020-01-03 13-17-17](https://user-images.githubusercontent.com/362891/71723028-661efe00-2e2b-11ea-8ebc-f41a9522f777.png)

**Comment by xuchunyang** [comment]
The directory part in the powerline theme was hard-coded and not customizable. I've just pushed a commit to let you customize it, e.g., this will do what you want

```el
(define-advice eshell-git-prompt-powerline-dir (:override () short)
  "Show only last directory."
  (file-name-nondirectory (directory-file-name default-directory)))
```

**Comment by rileyrg** [comment]
Thank you for your prompt response. But I'm sure not what it is I need to do.  I'm not much of an elisper.  I need to copy and paste that code above to my config? A defcustom seems to be the way to go where you specify the prompt path length akin to ` POWERLEVEL9K_SHORTEN_DIR_LENGTH=1`

OK, pasting that into my config worked I'll close. thanks.

**Comment by xuchunyang** [comment]
> I need to copy and paste that code above to my config?

Yes, but It's important to understand every line in your config.

The function `eshell-git-prompt-powerline-dir` returns the directory part of the powerline prompt, by default, it returns the full path like `~/src/emacs`, to make it returns only `emacs`, we can use [(elisp) Advising Functions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) which allow us modify function definition without modify its source code, for example, `foo` returns 1

```el
(defun foo () 1)

(foo)
;; => 1
```

what we need to do if we want it to return 2? We "override" its function definition with a new one:

```el
(defun bar () 2)
(advice-add 'foo :override #'bar)

(foo)
;; => 2
```

`define-advice` is a shorter way to write defun + advice-add.

> A defcustom seems to be the way to go where you specify the prompt path length akin to POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

Yes, that's more convenient for the user, but it requires more work from the developer.
